export const types = {
  GET_BROADCAST_SOCKET: "GET_BROADCAST_SOCKET",
  GET_INTERACTIVE_SOCKET: "GET_INTERACTIVE_SOCKET",
  GET_STRATEGY_SOCKET: "GET_STRATEGY_SOCKET",
  GET_BROADCAST_DATA: "GET_BROADCAST_DATA",
  ADD_LOG: "ADD_LOG",
  GET_LOG: "GET_LOG",
};
